version: "4.27"
services:
  
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Core:/app
    ports:
      - "8000:8000"
    # environment:
      # - POSTGRES_NAME=postgres
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
    # depends_on:
      # - db