version: "3.9"
services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: backend
    command: gunicorn myproject.wsgi --bind 0.0.0.0:8000
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - Debug=False
      - SECRET_KEY= test
    depends_on:
      - redis
    


  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports: 
      - "80:80"
    
    depends_on:
      - redis
      - backend
      





