version: "3.9"
services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
  

  db:
    image: postgres:latest
    container_name: POSTGRES_DB
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
     
    volumes:
      - ./data/db:/var/lib/postgresql/data/

  backend:
    build: .
    container_name: backend
    command: python manage.py makemigrations &&
            python manage.py migrate &&
            gunicorn Core.wsgi --bind 0.0.0.0:8000
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media

    expose:
      - "8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - SECRET_KEY=test
    depends_on:
      - redis
      - db
    networks:
      - default


  

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports: 
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      #app since in Dockerfile workdie is /app
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - redis
      - backend

# this is introduced common volume
volumes:
  static_volume:
  media_volume:



networks:
  default:
    driver: bridge

