# Generated by Django 4.2 on 2024-07-03 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 3, 7, 56, 51, 650505, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_date",
            field=models.DateTimeField(),
        ),
    ]
