# Generated by Django 4.2 on 2024-07-04 15:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_created_at_profile"),
        ("blog", "0006_alter_post_created_date_alter_post_updated_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.profile"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 4, 15, 5, 35, 143740, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
