# Generated by Django 4.2 on 2024-07-08 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_author_alter_post_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
